"""empty message

Revision ID: 38b6c6dc39cd
Revises: 790272f2e131
Create Date: 2023-05-15 21:38:12.194227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b6c6dc39cd'
down_revision = '790272f2e131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_model', schema=None) as batch_op:
        batch_op.drop_constraint('logs_model_classification_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_model', schema=None) as batch_op:
        batch_op.create_unique_constraint('logs_model_classification_key', ['classification'])

    # ### end Alembic commands ###
