"""empty message

Revision ID: 4119799763dd
Revises: c8fc33dff261
Create Date: 2023-06-23 15:48:19.267118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4119799763dd'
down_revision = 'c8fc33dff261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_model', schema=None) as batch_op:
        batch_op.alter_column('target',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_model', schema=None) as batch_op:
        batch_op.alter_column('target',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###
