"""empty message

Revision ID: 790272f2e131
Revises: 
Create Date: 2023-05-15 21:29:44.666225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790272f2e131'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_model', schema=None) as batch_op:
        batch_op.alter_column('log_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('logs_model', schema=None) as batch_op:
        batch_op.alter_column('log_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
