"""empty message

Revision ID: c8fc33dff261
Revises: ddf4c85cb471
Create Date: 2023-06-23 14:41:04.595723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fc33dff261'
down_revision = 'ddf4c85cb471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_model', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
